name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  checks:
    name: Run Checks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        command: [test, lint]
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9.15.4
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run ${{ matrix.command }}
        run: pnpm ${{ matrix.command }}

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: checks
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9.15.4
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Verify File Contents
        run: |
          cat src/modules/application/ui/components/ComponentEditor/components/editors/HeadingEditor.tsx
          echo "Current HEAD: $(git rev-parse HEAD)"

      - name: Build the app
        run: pnpm build
